# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull Request

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install -U poetry
          poetry install

      - name: Install license-header-checker
        run: curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash
      - name: Run license check
        run: ./bin/license-header-checker -a -r .github/license-header.txt . py && [[ -z `git status -s` ]]

#      - name: Lint
#        run: |
#          export PIP_USER=0; poetry run pre-commit run --all-files

      - name: Unit Tests
        run: |
          poetry run pytest -v --tb=short tests/unit-tests/

      - name: Integration Tests
        env:
          XATA_WORKSPACE_ID: ${{ secrets.INTEGRATION_TEST_WORKSPACE }}
          XATA_API_KEY: ${{ secrets.INTEGRATION_TEST_API_KEY }}
        run: |
          poetry run pytest -v --tb=short tests/integration-tests/
